VALID = "valid"
WARNING = "warning"
REJECTED = "rejected"

SUCCESS = "success"
FAILED = "failed"
SKIPPED = "skipped"

OK = "OK"
UNKNOWN_ERROR = "UNKNOWN_ERROR"

ALLOWED_RECORD_STATUSES = {VALID, WARNING, REJECTED}
ALLOWED_PROCESSING_STATUSES = {SUCCESS, WARNING, FAILED}
