SEGMENTATION_METHOD = "otsu"
FOREGROUND = "dark"
GAUSSIAN_BLUR_KERNEL = 5
MIN_OBJECT_SIZE_PX = 100
FILL_HOLES = True
REMOVE_SMALL_OBJECTS = True
SAVE_INTERMEDIATE_IMAGES = True
DEFAULT_OUTPUT_DIR = "outputs/analysis"
